
import java.text.DecimalFormat;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class PetshopGUI extends javax.swing.JFrame {

    //Declarar variáveis aqui!!
    String raca, sexo, porte;
    String[] pagamento = {"Cheque", "Cartão", "Dinheiro"};
    String[] parcelamento = {"Uma", "Duas", "Três"};
    int idade;
    double valorTotal;
    DecimalFormat df;

    ImageIcon c1 = new javax.swing.ImageIcon(getClass().getResource("/Dalmata.jpg"));
    ImageIcon c2 = new javax.swing.ImageIcon(getClass().getResource("/Doberman.jpg"));
    ImageIcon c3 = new javax.swing.ImageIcon(getClass().getResource("/Pinscher.png"));
    ImageIcon c4 = new javax.swing.ImageIcon(getClass().getResource("/Poodle.jpg"));
    ImageIcon c5 = new javax.swing.ImageIcon(getClass().getResource("/Outra.jpg"));

    public PetshopGUI() {
        initComponents();
        df = new DecimalFormat("#.##");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Porte = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcbRaca = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jcbSexo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jtfIdade = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jrbPequeno = new javax.swing.JRadioButton();
        jrbMedio = new javax.swing.JRadioButton();
        jrbGrande = new javax.swing.JRadioButton();
        jrbGigante = new javax.swing.JRadioButton();
        jbCalcular = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jtfParcelas = new javax.swing.JTextField();
        jtfTotal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jlCachorros = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PetShop VaiTotó");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Orçamento para Banho e Tosa");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Raça:");

        jcbRaca.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcbRaca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Dálmata", "Doberman", "Pinscher", "Poodle", "Outra" }));
        jcbRaca.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbRacaItemStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Sexo:");

        jcbSexo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "M", "F" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Idade:");

        jtfIdade.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Porte:");

        Porte.add(jrbPequeno);
        jrbPequeno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jrbPequeno.setText("Pequeno");
        jrbPequeno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbPequenoActionPerformed(evt);
            }
        });

        Porte.add(jrbMedio);
        jrbMedio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jrbMedio.setText("Médio");
        jrbMedio.setToolTipText("");
        jrbMedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbMedioActionPerformed(evt);
            }
        });

        Porte.add(jrbGrande);
        jrbGrande.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jrbGrande.setText("Grande");

        Porte.add(jrbGigante);
        jrbGigante.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jrbGigante.setText("Gigante");
        jrbGigante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbGiganteActionPerformed(evt);
            }
        });

        jbCalcular.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbCalcular.setText("Calcular Valor");
        jbCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCalcularActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Parcelas:");

        jtfParcelas.setEditable(false);
        jtfParcelas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jtfTotal.setEditable(false);
        jtfTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("De");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("R$");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbRaca, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(74, 74, 74)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jrbPequeno)
                                .addGap(28, 28, 28)
                                .addComponent(jrbMedio)
                                .addGap(33, 33, 33)
                                .addComponent(jrbGrande)
                                .addGap(18, 18, 18)
                                .addComponent(jrbGigante))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(jtfParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(36, 36, 36)
                                        .addComponent(jLabel7)
                                        .addGap(25, 25, 25)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                                .addComponent(jlCachorros, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jbCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlCachorros, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jcbRaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jcbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jtfIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jrbPequeno)
                            .addComponent(jrbMedio)
                            .addComponent(jrbGrande)
                            .addComponent(jrbGigante))
                        .addGap(27, 27, 27)
                        .addComponent(jbCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jtfParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jtfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrbGiganteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbGiganteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbGiganteActionPerformed

    private void jrbPequenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbPequenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbPequenoActionPerformed

    private void jrbMedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbMedioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbMedioActionPerformed

    private void jbCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCalcularActionPerformed
        // TODO add your handling code here:
        valorTotal = 0;
        raca = jcbRaca.getSelectedItem().toString();
        sexo = jcbSexo.getSelectedItem().toString();
        if (jrbPequeno.isSelected()) {
            porte = "Pequeno";
        }
        if (jrbMedio.isSelected()) {
            porte = "Médio";
        }
        if (jrbGrande.isSelected()) {
            porte = "Grande";
        }
        if (jrbGigante.isSelected()) {
            porte = "Gigante";
        }
        idade = Integer.parseInt(jtfIdade.getText());
        switch (raca) {
            case "Dálmata":
                valorTotal = valorTotal + 100;
                break;
            case "Doberman":
                valorTotal = valorTotal + 80;
                break;
            case "Pinscher":
                valorTotal = valorTotal + 60;
                break;
            case "Poodle":
                valorTotal = valorTotal + 85;
                break;
            case "Outra":
                valorTotal = valorTotal + 90;
                break;
        }

        switch (sexo) {
            case "M":
                valorTotal = valorTotal + 50;
                break;
            case "F":
                valorTotal = valorTotal + 40;
                break;
        }

        switch (idade) {
            case 1:
                valorTotal = valorTotal + 10;
                break;
            case 2:
                valorTotal = valorTotal + 12;
                break;
            case 3:
                valorTotal = valorTotal + 14;
                break;
            case 4:
                valorTotal = valorTotal + 16;
                break;
            case 5:
                valorTotal = valorTotal + 20;
                break;
            case 6:
                valorTotal = valorTotal + 25;
                break;
            default:
                valorTotal = valorTotal + 35;
                break;
        }

        switch (porte) {
            case "Pequeno":
                valorTotal = valorTotal + 50;
                break;
            case "Médio":
                valorTotal = valorTotal + 80;
                break;
            case "Grande":
                valorTotal = valorTotal + 110;
                break;
            case "Gigante":
                valorTotal = valorTotal + 150;
                break;
        }

        int p = JOptionPane.showOptionDialog(null, "Informe a Opção de Pagamento", "Pagamento", 1, 3, null, pagamento, null);
        switch (p) {
            case 1:
                valorTotal = valorTotal + (valorTotal * 0.02);
                break;
            case 2:
                valorTotal = valorTotal - (valorTotal * 0.05);
                break;
        }

        int op = 1;
        if ((valorTotal > 200)) {
            op = JOptionPane.showOptionDialog(null, "Deseja fazer em quantas vezes?", "Parcelamento", 1, 3, null, parcelamento, null);
            switch (op) {
                case 1:
                    valorTotal = valorTotal / 2;

                    break;
                case 2:
                    valorTotal = valorTotal / 3;

                    break;
            }
        }
        jtfParcelas.setText(op + 1 + "");
        jtfTotal.setText(df.format(valorTotal));
    }//GEN-LAST:event_jbCalcularActionPerformed

    private void jcbRacaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbRacaItemStateChanged
        // TODO add your handling code here:
        
        
        switch (jcbRaca.getSelectedItem().toString()) {
            case "Dálmata":
                jlCachorros.setIcon(c1);
                break;
            case "Doberman":
                jlCachorros.setIcon(c2);
                break;
            case "Pinscher":
                jlCachorros.setIcon(c3);
                break;
            case "Poodle":
                jlCachorros.setIcon(c4);
                break;
            case "Outra":
                jlCachorros.setIcon(c5);
                break;
        }

    }//GEN-LAST:event_jcbRacaItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PetshopGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PetshopGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PetshopGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PetshopGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PetshopGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Porte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton jbCalcular;
    private javax.swing.JComboBox<String> jcbRaca;
    private javax.swing.JComboBox<String> jcbSexo;
    private javax.swing.JLabel jlCachorros;
    private javax.swing.JRadioButton jrbGigante;
    private javax.swing.JRadioButton jrbGrande;
    private javax.swing.JRadioButton jrbMedio;
    private javax.swing.JRadioButton jrbPequeno;
    private javax.swing.JTextField jtfIdade;
    private javax.swing.JTextField jtfParcelas;
    private javax.swing.JTextField jtfTotal;
    // End of variables declaration//GEN-END:variables
}
